### ISSUE TITLE
Python highlighting inconsistent

### ISSUE THREAD

**Issue by amykyta3** [evandrocoan/Sublime3-Theme-NotepadPlusPlus#2]
Sometimes identifiers are highlighted pink. Seems to not happen if they are enclosed in parentheses and they show up correctly as black.

See annotated areas in screenshot below:
![screenshot from 2018-05-20 12-19-39](https://user-images.githubusercontent.com/12021539/40282771-e818d056-5c28-11e8-970a-918256f667ad.png)

Using Sublimetext v3.1.1, build 3176
Notepad++ Color Scheme v2.0.3

Thanks again for the color scheme!
Cheers.

**Comment by evandrocoan** [comment]
![image](https://user-images.githubusercontent.com/5332158/40282994-b54673ca-5c4d-11e8-998a-0e8eddb6900a.png)


When comparing both scopes, we got the if's one missing the `function-call` scoping. I could fix this by removing the scope `function-call` from the colors.
```
source.python meta.qualified-name.python meta.generic-name.python 
source.python meta.function-call.python meta.function-call.arguments.python meta.qualified-name.python meta.generic-name.python 
source.python meta.function-call.python meta.function-call.arguments.python meta.qualified-name.python meta.generic-name.python 
source.python meta.statement.if.python meta.qualified-name.python meta.generic-name.python 
source.python meta.qualified-name.python meta.generic-name.python 
source.python meta.qualified-name.python meta.generic-name.python 
```

```python
#! /usr/bin/env python
# -*- coding: utf-8 -*-

class Stuff():
    attribute = None

    def add(self):
        local_var = None
        sorted(self.attribute, local_var)

        if self.attribute:
            self.attribute( local_var.varing )
            self.attribute = local_var.varing
```


Related:

1. https://github.com/sublimehq/Packages/issues/1441 [Python] Poor invalid scopes while typing

**Comment by evandrocoan** [comment]
I improved a little the coloring, but this is also a issue on the Sublime Text Python Syntax. I opened a issue there reporting it.

**Comment by evandrocoan** [comment]
This should fix it, but I am not sure whether it breaks it for other languages other than python. Then, I let a comment over it referring this, in case it causes problems.

You should receive the update in a few hours.
